/**
 * 插件市场模拟数据
 */

import type { TypePackage, ThemePackage, OtherPlugin } from './types';

/** 类型包数据 */
export const TYPE_PACKAGES: TypePackage[] = [
    {
        id: 'client',
        pluginType: 'type-package',
        name: '客户管理',
        version: '1.0.0',
        description: '标准客户关系管理类型包，包含客户基本信息、联系方式、跟进记录等数据块',
        author: 'ATLAS Official',
        category: 'business',
        icon: 'building',
        color: '#3B82F6',
        downloads: 1234,
        rating: 4.8,
        installed: true,
        isOfficial: true,
        tags: ['CRM', '客户', '销售', 'B2B'],
        updatedAt: '2026-01-04',
        defaultFunction: 'entity_detail',
        defaultDisplay: 'detail.card',
        blocksCount: 4,
    },
    {
        id: 'contact',
        pluginType: 'type-package',
        name: '联系人',
        version: '1.0.0',
        description: '联系人信息管理，支持多联系方式、标签分组',
        author: 'ATLAS Official',
        category: 'business',
        icon: 'user',
        color: '#8B5CF6',
        downloads: 986,
        rating: 4.7,
        installed: true,
        isOfficial: true,
        tags: ['联系人', '通讯录'],
        updatedAt: '2026-01-04',
        defaultFunction: 'entity_detail',
        defaultDisplay: 'detail.card',
        blocksCount: 3,
    },
    {
        id: 'project',
        pluginType: 'type-package',
        name: '项目管理',
        version: '1.0.0',
        description: '项目全生命周期管理，包含里程碑、任务、进度追踪',
        author: 'ATLAS Official',
        category: 'business',
        icon: 'folder',
        color: '#10B981',
        downloads: 2156,
        rating: 4.9,
        installed: true,
        isOfficial: true,
        tags: ['项目', '任务', '进度'],
        updatedAt: '2026-01-04',
        defaultFunction: 'entity_detail',
        defaultDisplay: 'detail.card',
        blocksCount: 5,
    },
    {
        id: 'task',
        pluginType: 'type-package',
        name: '任务清单',
        version: '1.0.0',
        description: '待办任务管理，支持优先级、截止日期、状态追踪',
        author: 'ATLAS Official',
        category: 'business',
        icon: 'check-square',
        color: '#F59E0B',
        downloads: 1567,
        rating: 4.6,
        installed: true,
        isOfficial: true,
        tags: ['任务', '待办', 'GTD'],
        updatedAt: '2026-01-04',
        defaultFunction: 'entity_detail',
        defaultDisplay: 'detail.form',
        blocksCount: 2,
    },
    {
        id: 'article',
        pluginType: 'type-package',
        name: '文章',
        version: '1.0.0',
        description: '长文本内容创作，支持目录、阅读模式、字数统计',
        author: 'ATLAS Official',
        category: 'content',
        icon: 'file-text',
        color: '#EC4899',
        downloads: 3421,
        rating: 4.9,
        installed: true,
        isOfficial: true,
        tags: ['文章', '博客', '写作'],
        updatedAt: '2026-01-04',
        defaultFunction: 'article',
        defaultDisplay: 'article.single',
        blocksCount: 3,
    },
    {
        id: 'note',
        pluginType: 'type-package',
        name: '笔记',
        version: '1.0.0',
        description: '知识记录和灵感捕捉，轻量级快速记录',
        author: 'ATLAS Official',
        category: 'content',
        icon: 'sticky-note',
        color: '#14B8A6',
        downloads: 4532,
        rating: 4.8,
        installed: true,
        isOfficial: true,
        tags: ['笔记', '知识管理'],
        updatedAt: '2026-01-04',
        defaultFunction: 'wiki',
        defaultDisplay: 'article.double',
        blocksCount: 2,
    },
    {
        id: 'event',
        pluginType: 'type-package',
        name: '日程事件',
        version: '1.0.0',
        description: '日程、会议、提醒管理，支持日历视图',
        author: 'ATLAS Official',
        category: 'business',
        icon: 'calendar',
        color: '#EF4444',
        downloads: 876,
        rating: 4.5,
        installed: true,
        isOfficial: true,
        tags: ['日程', '会议', '提醒'],
        updatedAt: '2026-01-04',
        defaultFunction: 'entity_detail',
        defaultDisplay: 'detail.form',
        blocksCount: 2,
    },
    {
        id: 'album',
        pluginType: 'type-package',
        name: '相册',
        version: '1.0.0',
        description: '图片集合管理，支持画廊视图',
        author: 'ATLAS Official',
        category: 'content',
        icon: 'images',
        color: '#F97316',
        downloads: 654,
        rating: 4.4,
        installed: true,
        isOfficial: true,
        tags: ['相册', '图片', '媒体'],
        updatedAt: '2026-01-04',
        defaultFunction: 'gallery',
        defaultDisplay: 'gallery.masonry',
        blocksCount: 2,
    },
    // 市场类型包
    {
        id: 'supplier',
        pluginType: 'type-package',
        name: '供应商管理',
        version: '1.0.0',
        description: '供应商档案管理，包含资质、合作记录、评估',
        author: 'ATLAS Official',
        category: 'business',
        icon: 'building',
        color: '#6366F1',
        downloads: 432,
        rating: 4.6,
        installed: false,
        isOfficial: true,
        tags: ['供应商', '采购', '供应链'],
        updatedAt: '2026-01-03',
        defaultFunction: 'entity_detail',
        defaultDisplay: 'detail.card',
        blocksCount: 4,
    },
    {
        id: 'product',
        pluginType: 'type-package',
        name: '产品管理',
        version: '1.0.0',
        description: '产品信息管理，包含规格、价格、库存',
        author: 'ATLAS Official',
        category: 'business',
        icon: 'folder-open',
        color: '#0EA5E9',
        downloads: 765,
        rating: 4.7,
        installed: false,
        isOfficial: true,
        tags: ['产品', '商品', '库存'],
        updatedAt: '2026-01-02',
        defaultFunction: 'entity_list',
        defaultDisplay: 'list.card',
        blocksCount: 5,
    },
    {
        id: 'order',
        pluginType: 'type-package',
        name: '订单管理',
        version: '1.0.0',
        description: '订单全流程管理，包含商品明细、物流追踪',
        author: 'ATLAS Official',
        category: 'business',
        icon: 'file-text',
        color: '#84CC16',
        downloads: 543,
        rating: 4.5,
        installed: false,
        isOfficial: true,
        tags: ['订单', '交易', '电商'],
        updatedAt: '2026-01-01',
        defaultFunction: 'entity_detail',
        defaultDisplay: 'detail.form',
        blocksCount: 4,
    },
    {
        id: 'employee',
        pluginType: 'type-package',
        name: '员工档案',
        version: '1.0.0',
        description: '员工信息管理，包含部门、职位、联系方式',
        author: 'Community',
        category: 'business',
        icon: 'user',
        color: '#A855F7',
        downloads: 321,
        rating: 4.3,
        installed: false,
        isOfficial: false,
        tags: ['员工', '人事', 'HR'],
        updatedAt: '2025-12-28',
        defaultFunction: 'entity_detail',
        defaultDisplay: 'detail.card',
        blocksCount: 3,
    },
    {
        id: 'meeting',
        pluginType: 'type-package',
        name: '会议纪要',
        version: '1.0.0',
        description: '会议记录模板，包含议程、决议、待办',
        author: 'Community',
        category: 'content',
        icon: 'calendar',
        color: '#F43F5E',
        downloads: 234,
        rating: 4.2,
        installed: false,
        isOfficial: false,
        tags: ['会议', '纪要', '协作'],
        updatedAt: '2025-12-25',
        defaultFunction: 'article',
        defaultDisplay: 'article.single',
        blocksCount: 3,
    },
];

/** 主题包数据 */
export const THEME_PACKAGES: ThemePackage[] = [
    {
        id: 'atlas-default',
        pluginType: 'theme-package',
        name: 'ATLAS 默认',
        version: '1.0.0',
        description: '系统默认主题，简洁专业的设计风格',
        author: 'ATLAS Official',
        icon: 'sun',
        color: '#3B82F6',
        downloads: 5000,
        rating: 4.9,
        installed: true,
        isOfficial: true,
        tags: ['默认', '简洁', '专业'],
        updatedAt: '2026-01-04',
        mode: 'both',
        previewColors: ['#3B82F6', '#1E40AF', '#DBEAFE', '#EFF6FF'],
    },
    {
        id: 'dark-pro',
        pluginType: 'theme-package',
        name: '暗黑专业版',
        version: '1.0.0',
        description: '专业级深色主题，适合长时间工作，护眼设计',
        author: 'ATLAS Official',
        icon: 'moon',
        color: '#1E293B',
        downloads: 2345,
        rating: 4.8,
        installed: true,
        isOfficial: true,
        tags: ['深色', '护眼', '专业'],
        updatedAt: '2026-01-03',
        mode: 'dark',
        previewColors: ['#1E293B', '#334155', '#94A3B8', '#F8FAFC'],
    },
    {
        id: 'notion-style',
        pluginType: 'theme-package',
        name: 'Notion 风格',
        version: '1.0.0',
        description: '借鉴 Notion 的简约设计，清新自然',
        author: 'Community',
        icon: 'sparkles',
        color: '#000000',
        downloads: 1876,
        rating: 4.7,
        installed: false,
        isOfficial: false,
        tags: ['Notion', '简约', '清新'],
        updatedAt: '2025-12-30',
        mode: 'light',
        previewColors: ['#FFFFFF', '#F7F6F3', '#37352F', '#2EAADC'],
    },
    {
        id: 'github-theme',
        pluginType: 'theme-package',
        name: 'GitHub 风格',
        version: '1.0.0',
        description: '借鉴 GitHub 的设计语言，适合开发者',
        author: 'Community',
        icon: 'layout',
        color: '#24292F',
        downloads: 1234,
        rating: 4.6,
        installed: false,
        isOfficial: false,
        tags: ['GitHub', '开发者', '代码'],
        updatedAt: '2025-12-28',
        mode: 'both',
        previewColors: ['#24292F', '#0969DA', '#F6F8FA', '#1F2328'],
    },
    {
        id: 'ocean-breeze',
        pluginType: 'theme-package',
        name: '海洋微风',
        version: '1.0.0',
        description: '清新的蓝绿色调，给人宁静舒适的感觉',
        author: 'Community',
        icon: 'palette',
        color: '#0891B2',
        downloads: 876,
        rating: 4.5,
        installed: false,
        isOfficial: false,
        tags: ['蓝绿', '清新', '宁静'],
        updatedAt: '2025-12-25',
        mode: 'light',
        previewColors: ['#0891B2', '#06B6D4', '#CFFAFE', '#ECFEFF'],
    },
    {
        id: 'sunset-glow',
        pluginType: 'theme-package',
        name: '日落余晖',
        version: '1.0.0',
        description: '温暖的橙红色调，充满活力和热情',
        author: 'Community',
        icon: 'sun',
        color: '#EA580C',
        downloads: 654,
        rating: 4.4,
        installed: false,
        isOfficial: false,
        tags: ['橙色', '温暖', '活力'],
        updatedAt: '2025-12-20',
        mode: 'light',
        previewColors: ['#EA580C', '#F97316', '#FED7AA', '#FFF7ED'],
    },
];

/** 其他插件数据 */
export const OTHER_PLUGINS: OtherPlugin[] = [
    {
        id: 'ai-assistant',
        pluginType: 'other',
        name: 'AI 智能助手',
        version: '1.0.0',
        description: '集成 AI 能力，支持智能写作、内容生成、数据分析',
        author: 'ATLAS Official',
        icon: 'sparkles',
        color: '#8B5CF6',
        downloads: 3456,
        rating: 4.9,
        installed: true,
        isOfficial: true,
        tags: ['AI', '智能', '写作'],
        updatedAt: '2026-01-04',
        capabilities: ['智能写作', '内容生成', '数据分析', '自动摘要'],
    },
    {
        id: 'export-plus',
        pluginType: 'other',
        name: '导出增强',
        version: '1.0.0',
        description: '增强的导出功能，支持 PDF、Word、Markdown 等多种格式',
        author: 'ATLAS Official',
        icon: 'file-text',
        color: '#10B981',
        downloads: 2345,
        rating: 4.7,
        installed: true,
        isOfficial: true,
        tags: ['导出', 'PDF', 'Word'],
        updatedAt: '2026-01-03',
        capabilities: ['PDF导出', 'Word导出', 'Markdown导出', '批量导出'],
    },
    {
        id: 'sync-cloud',
        pluginType: 'other',
        name: '云同步',
        version: '1.0.0',
        description: '多设备云同步，支持增量同步和冲突解决',
        author: 'ATLAS Official',
        icon: 'zap',
        color: '#3B82F6',
        downloads: 1876,
        rating: 4.6,
        installed: false,
        isOfficial: true,
        tags: ['同步', '云端', '多设备'],
        updatedAt: '2026-01-02',
        capabilities: ['实时同步', '增量同步', '冲突解决', '版本历史'],
    },
    {
        id: 'integration-api',
        pluginType: 'other',
        name: 'API 集成',
        version: '1.0.0',
        description: '第三方服务集成，支持 Webhook、REST API 调用',
        author: 'Community',
        icon: 'puzzle',
        color: '#F59E0B',
        downloads: 987,
        rating: 4.4,
        installed: false,
        isOfficial: false,
        tags: ['API', '集成', 'Webhook'],
        updatedAt: '2025-12-28',
        capabilities: ['Webhook', 'REST API', '自动化', '数据导入'],
    },
    {
        id: 'backup-tool',
        pluginType: 'other',
        name: '备份工具',
        version: '1.0.0',
        description: '自动备份和恢复，支持本地和云端备份',
        author: 'Community',
        icon: 'folder',
        color: '#EF4444',
        downloads: 765,
        rating: 4.3,
        installed: false,
        isOfficial: false,
        tags: ['备份', '恢复', '安全'],
        updatedAt: '2025-12-25',
        capabilities: ['自动备份', '手动备份', '云端备份', '一键恢复'],
    },
];

